# Generated by Django 6.0 on 2026-01-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="original_country",
            new_name="origin_country",
        ),
    ]
