# Generated by Django 6.0 on 2026-01-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="count_like",
            field=models.IntegerField(default=0),
        ),
    ]
