# Generated by Django 6.0 on 2026-01-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_like_count_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="backdrop_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="origin_country",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="original_language",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="original_title",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=512),
        ),
    ]
