# Generated by Django 6.0 on 2026-01-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "movies",
            "0007_alter_movie_backdrop_path_alter_movie_origin_country_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="count_like",
        ),
        migrations.AddField(
            model_name="movie",
            name="count_like",
            field=models.IntegerField(default=0),
        ),
    ]
