# Generated by Django 6.0 on 2025-12-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="comment",
            unique_together=set(),
        ),
    ]
