# Generated by Django 6.0 on 2026-01-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_rename_original_country_movie_origin_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="spoken_language",
            new_name="spoken_languages",
        ),
    ]
