# Generated by Django 6.0 on 2026-01-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_rename_spoken_language_movie_spoken_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="runtime",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
